### ISSUE TITLE
What is the semantics of this symbol `:`

### ISSUE THREAD

**Issue by JIM-GLITCH** [Mercury-Language/mercury#111]
https://github.com/Mercury-Language/mercury/blob/726da4f03c57653d02de1d8e46056037dcd6a96d/library/parsing_utils.m#L952
I don't know what this symbol `:` means. Any explanation would be appreciated.

**Comment by JIM-GLITCH** [comment]
Thank you.

**Comment by juliensf** [comment]
That's section 2.15.7 of the reference manual for the current stable release (22.01.X).
For the ROTDs, explicit type qualification is now covered in section 3.3.
