### ISSUE TITLE
posix library incompatible with --intermodule-optimization?

### ISSUE THREAD

**Issue by poldy** [Mercury-Language/mercury#116]
I installed the posix library by going into "extras/posix" and running `make install`.

Given a minimal example like

```mercury
:- module hello.
:- interface.
:- import_module io.
:- pred main(io::di, io::uo) is det.
:- implementation.
:- import_module posix, posix.sleep.

main(!IO) :-
    posix.sleep.sleep(1u, _, !IO),
    io.write_string("Hello, world!\n", !IO).
```

and a Mercury.options of

```
MCFLAGS = -O6 --intermodule-optimization
GRADEFLAGS = --grade hlc.gc
EXTRA_LIBRARIES = posix
```

I get the following error:

```
mercury_compile: cannot find `Mercury/int0s/posix.int0' in directories .,
  /usr/lib/mercury/ints
```

Removing "--intermodule-optimization" fixes the problem. I've reproduced this with -O5, -O4 and -O1. And with both the hlc.gc and hlc.par.gc grades.

This is on Ubuntu 22.04, with Mercury 22.01 from the package repo (I downloaded the corresponding source release to install "posix"). I'm also able to reproduce on macOS Ventura with 22.01.5 from Homebrew.

**Comment by poldy** [comment]
By the way, this was all using "mmc --make" to build.

**Comment by juliensf** [comment]
The error can be avoided by compiling and installing the posix library with `--intermodule-optimization`.
Without that option being specified, `posix.int0` is not installed, which I think is a bug in `mmc --make`.

**Comment by poldy** [comment]
That worked, thanks. You can close this ticket if you like, or leave it open to cover a `mmc --make` bug.
