### ISSUE TITLE
Possibility of adding Go as a new backend

### ISSUE THREAD

**Issue by maxnordlund** [Mercury-Language/mercury#16]
Hi, I've stumbled into Mercury a couple of weeks ago and was very happy to see their is a strongly typed and moded logical programming language. I've was even more happy to see that it could compiled into high-level C, allowing it to be integrated into pretty much anything.

That got me thinking about using it with [Go][], and after thinking about it for a while I realized that it might be a good fit as a backend for Mercury. For those of you who haven't heard about [Go][] its defining feature is the builtin concurrency primitives channels and goroutines, which basically are micro-threads. There are some other nice to have things, like garbage collection, exceptions, and returning multiple results.

This seams to fit Mercurys high-level C compiler infrastructure well. So my question is, do you think it would be a good backend language for Mercury? And if so how much work would it be to add it?

I'll of course help as much as I can, but I'm not a compiler person just yet. But for the [Go][] parts I know then by heart now, since it's my current go-to language.

[Go]: https://golang.org/

**Comment by zsomogyi** [comment]
This proposal seems to have gone nowhere.
