### ISSUE TITLE
'mdb: are you sure you want to quit?' prompt is inconsistent and annoying

### ISSUE THREAD

**Issue by ulidtko** [Mercury-Language/mercury#28]
Very simple: enter `mdb` `query`, then try to exit in the fastest possible way.

My best is **four keystrokes**, which is way over the top. ^D from `query`, once more ^D from `mdb` (this is the point where ideally we're done), now the stupid prompt appears, and we have no other way than to hit `y` and `↵`.

```
?- 
mdb> mdb: are you sure you want to quit? y
```

I call this kind of prompt "stupid" because it makes no sense: anyone sane would save everything valuable **before** trying to exit from a program. Exactly like in [this question][*] of mine, but for R. A surprising amount of people are annoyed by this stupid prompt.

[*]: http://stackoverflow.com/questions/4996090/how-to-disable-save-workspace-image-prompt-in-r

It's also inconsistent, because ^D from `query` doesn't prompt, while ^D from `mdb` does.

Finally, I accept the argument that the primary purpose of the prompt is to prevent data loss on accidental EOF input. However, I'm not convinced that intentionally tripping up users is worth the purpose in case of `mdb`; what data is there to lose?.. And what if I *accidentally* input an `rm *` in my shell — who's there to blame for data loss except me and my, so to say, sloppy input habits?

Four-keystroke exit does seriously kick me, up to the point that I want to `kill -9` instead of exiting like a civil.

**Comment by zsomogyi** [comment]
You may find this prompt stupid, but lots of people find it prevents them from losing
the state of a possibly-quite-long debugger session due to a typo.

If you find this stupid, use "quit -y", or an alias that expands to "quit -y".

I find it strange that you object to typing four characters, but then wrote all the text above
to complain about it.

**Comment by ulidtko** [comment]
> lots of people find it prevents them from losing... due to a typo

How much evidence do you *actually* have for that claim?

For as you can see, at least 47 people agree to the contrary in the exactly similar [case for R][*].

[*]: http://stackoverflow.com/questions/4996090/how-to-disable-save-workspace-image-prompt-in-r
---

Then, EOF input shouldn't be ever considered a typo, I explained that above. If I'm not capable of using the keyboard reliably, my best bet would be to avoid any shortcuts at all, and exit via explicit `quit`. I'm fine with `quit` prompting "are you sure?".

But If I do already hold the Control key, it means I know what I'm doing. Programs re-asking "are you sure?" on shortcuts intentionally slow me down -- that defeats the whole point of keyboard shortcuts!

---
> I find it strange that you object to typing four characters, but then wrote all the text above to complain about it.

It's a pity I need to explain this. Complaint is written **once** and for all; extra keystrokes (+ angry return wear) occur **every time** *every one* exits the shell. Is that clear?
