### ISSUE TITLE
No check for capitalized predicate names — leads to confusing error message

### ISSUE THREAD

**Issue by ulidtko** [Mercury-Language/mercury#32]
I accidentally did a very simple error: named a predicate with `FooBar` instead of `fooBar`. You know, it's so easy to forget local naming conventions for a moment, when one is thinking hard about something else.

For such a simple error though, the compiler error messages... could be better. I was actually so confused by them that had to reduce step-by-step the whole program text to just 2 lines (recompiling after each tiniest edit) — until I realized what my error was all about.

```
hello.m:010: Error: some but not all arguments have modes.
hello.m:011: Error: clause for predicate `hello.'/3
hello.m:011:   without preceding `pred' declaration.
hello.m:011: Error: no mode declaration for predicate `'/3.
hello.m:011:   (Use `--infer-modes' to enable mode inference.)
hello.m:011: In clause for predicate `hello.'/3:
hello.m:011:   warning: variable `FooBar' occurs only once in this scope.
hello.m:011: Inferred :- pred ''(T1, int, int).
```

All caused by this:

    :- pred FooBar(int::in, int::out) is nondet.
    FooBar(0, 0).

Is this even valid syntax?..

In a non-contrived code environment, with more arguments of fancy types (and type variables!) with non-trivial names, it may be hard to notice the incorrect capitalization. Syntax highlighting could help, but my editor had none for Mercury.

A better error message could help in this issue.

**Comment by mgudemann** [comment]
> Is this even valid syntax?..

No, this is why the compiler complains. In Mercury, like in Prolog, uppercase names denote logic variables.

I suggest you go to the users mailing-list, which is much better suited for the kind of questions you have: https://www.mercurylang.org/lists/listinfo/users

**Comment by zsomogyi** [comment]
The next release will generate a more specific message for such errors.

**Comment by ulidtko** [comment]
Thanks!
