### ISSUE TITLE
Unresolved external in libgc on Windows when compiling with cl.exe

### ISSUE THREAD

**Issue by AlaskanEmily** [Mercury-Language/mercury#43]
When compiling the latest srcdist on Windows using MSVC 2015 as the C compiler, I get the following error when libgc is actually linked to any object:

libgc.lib(misc.obj) : error LNK2019: unresolved external symbol __imp__MessageBoxA@16 referenced in function _GC_win32_MessageBoxA

I suspect that either libgc should be configured differently, or the Mercury compile script should also link in User32.lib when compiling with cl (which I've hacked in as a workaround, and I can confirm it fixes the issue).

**Comment by wangp** [comment]
Can you try this change?

```
diff --git a/boehm_gc/Makefile.direct b/boehm_gc/Makefile.direct
index f2c603ec..1e683101 100644
--- a/boehm_gc/Makefile.direct
+++ b/boehm_gc/Makefile.direct
@@ -96,7 +96,7 @@ AO_SRC_DIR=$(srcdir)/libatomic_ops
 # Mercury-specific CFLAGS:
 # We need $(CFLAGS_FOR_PIC) because we might be building a shared library.
 CFLAGS= -I$(srcdir)/include -I$(AO_SRC_DIR)/src \
-	-DNO_EXECUTE_PERMISSION \
+	-DNO_EXECUTE_PERMISSION -DDONT_USE_USER32_DLL \
 	$(BOEHM_CFLAGS) $(CFLAGS_FOR_PIC) $(DLL_CFLAGS) $(EXTRA_CFLAGS)
 
 # If we are in the gcd grade then don't define -DNO_DEBUGGING
```

**Comment by wangp** [comment]
I see, the MSVC port uses boehm_gc/NT_MAKEFILE or even boehm/gc.mak instead. You could add -DDONT_USE_USER32_DLL to NT_MAKEFILE for now.

**Comment by wangp** [comment]
This is fixed now. Thanks for the report.
