### ISSUE TITLE
CYGWIN compatibility with fd_set when bootstrapping in mercury_reg_workarounds.h

### ISSUE THREAD

**Issue by C4Cypher** [Mercury-Language/mercury#49]
When bootstrapping on Windows 7 (32bit) with Cygwin (gcc-i686), bootstrapping install failed to compile runtime/mercury_reg_workarounds.h due to undefined type 'fd_set'.  

As suggested in https://github.com/curl/curl/issues/749 I was able to work around this by adding 
'#include <sys/select.h>   /* C4Cypher: for fd_set */' 

directly under line 17:
'#include <sys/types.h>		/* for fd_set */' 

in mercury_reg_workarounds.h.  Please let me know if there's any way I can assist with this.  Granted, this isn't a major issue, I just wanted to document that I ran into it and found a workaround.

**Comment by wangp** [comment]
Thanks for the report. I've pushed a fix.
