### ISSUE TITLE
Assert in the compiler with a promise and a typeclass instance

### ISSUE THREAD

**Issue by AlaskanEmily** [Mercury-Language/mercury#50]
A reduced test case is found here:

https://gist.github.com/AlaskanEmily/7265fdb96201ce6a4b6c4be87922c7bf

Compiling `mmc --make libtest` yields:
Software Error: hlds.assertion: predicate `hlds.assertion.record_preds_used_in'/4: Unexpected: invalid pred_id
** Error making `Mercury\cs\test.test.c'.

The assert seems to be caused by having both the promise and the typeclass instance in a submodule (it does not occur if the instance is in the main module). It is interesting that the promise is about a different predicate than what is used in the typeclass, though.

I would be more than willing to look into this (any advice on where to begin investigating would be appreciated), since it's hitting some of my actual code. I can just remove the promise in the module, but still the compiler shouldn't assert.

**Comment by wangp** [comment]
Right, the compiler should not abort so this is a bug.

However, you can just remove the promise as it won't be doing anything for you in practice. While the promise syntax is general (too general, IMHO), only certain forms are recognised and used for the accumulator introduction optimisation; your promise is none of those (if the promise is the same in the test case as your real program).

Someone will correct me if I am wrong.

**Comment by juliensf** [comment]
Fixed in commit c4dce74bb4b354ba01d65111e49b575f70e63298.
The fix is available in rotd-2018-10-03 onwards.
