### ISSUE TITLE
Is it possible for Mercury to compile to Javascript?

### ISSUE THREAD

**Issue by PolyPik** [Mercury-Language/mercury#60]
I know that Mercury currently does not support that language, but in theory is it possible to compile to an interpreted language like Javascript, Python, or PHP?

**Comment by zsomogyi** [comment]
Yes, of course; any Turing-complete language can be compiled to any other Turing-complete language. Whether it is a good idea is a different question.

**Comment by WojciechKarpiel** [comment]
Note for my fellow travellers finding this place in search for Mercury for the web:
There was an attempt at Mercury to WebAssembly compilation in 2020: [see the mailing list archives](https://lists.mercurylang.org/archives/reviews/2020-March/021184.html)
