### ISSUE TITLE
Configure script accepts system installed Mercury which cannot compile current source

### ISSUE THREAD

**Issue by AlaskanEmily** [Mercury-Language/mercury#62]
Using rotd-2019-01-21 to try to compile the current source yields the following errors trying to compile the standard library:

calendar.m:869: Error: the first argument of the `disable_warning' keyword
calendar.m:869:   should be the name of a warning to disable. The term
calendar.m:869:   `suspicious_recursion' is not the name of a warning.
calendar.m:881: Error: the first argument of the `disable_warning' keyword
calendar.m:881:   should be the name of a warning to disable. The term
calendar.m:881:   `suspicious_recursion' is not the name of a warning.
calendar.m:1107: Error: the first argument of the `disable_warning' keyword
calendar.m:1107:   should be the name of a warning to disable. The term
calendar.m:1107:   `suspicious_recursion' is not the name of a warning.
calendar.m:1122: Error: the first argument of the `disable_warning' keyword
calendar.m:1122:   should be the name of a warning to disable. The term
calendar.m:1122:   `suspicious_recursion' is not the name of a warning.
calendar.m:1137: Error: the first argument of the `disable_warning' keyword
calendar.m:1137:   should be the name of a warning to disable. The term
calendar.m:1137:   `suspicious_recursion' is not the name of a warning.

**Comment by zsomogyi** [comment]
Thanks for reporting this. I have updated the "is the compiler sufficiently recent" test
in the configure script.
