### ISSUE TITLE
Assert in the compiler with certain func modes

### ISSUE THREAD

**Issue by AlaskanEmily** [Mercury-Language/mercury#64]
A reduced test case is found here:

https://gist.github.com/AlaskanEmily/4e74f513f3ce9f2f1e5c9136f016825b

The error is:

`Software Error: check_hlds.cse_detection: predicate 'check_hlds.cse_detection.detect_cse_in_proc'/4: Unexpected: mode check fails when repeated`

It seems to be caused by the `:- mode (in, di) = (uo) is det.`

**Comment by zsomogyi** [comment]
Thanks for reporting the problem. Commit 2466524308930c380483a90c7d767a74e7c8507b
should fix it; it should appear in an ROTD in a day or two.

**Comment by AlaskanEmily** [comment]
Thanks for the quick response and fix!
