### ISSUE TITLE
hello world sample produce error at mmc

### ISSUE THREAD

**Issue by wetndusty** [Mercury-Language/mercury#79]
hw.m:001: Error: source file `hw.m' contains module named `hello'.

don`t know what to do

**Comment by PaulBone** [comment]
Hi @wetndusty, Try naming the file `hello.m` and make sure you build the program with `mmc --make'.  The --make option takes the program name as an argument and not the source file name. So you may have `hello.m` as a source file but you're asking Mercury to build the `hello` program.

    $ ls
    hello.m
    $ mmc --make hello

Hope this helps.

**Comment by ACleverDisguise** [comment]
Perhaps someone who can talk to actual people should be answering issues for Mercury instead of someone who's an arrogant jackass.
