### ISSUE TITLE
Suggest fix to maintain bootstrapping

### ISSUE THREAD

**Issue by fabnicol** [Mercury-Language/mercury#93]
[0001-patched-configure.ac.patch.gz](https://github.com/Mercury-Language/mercury/files/5897074/0001-patched-configure.ac.patch.gz)

Issue: mmc can no longer be bootstrapped by configuring with --enable-minimal-install 
          ROTDs and github master branch will not build using 20.06.1
Cause: since commit c32ed67e2098, Aug 21st 2020. 
Suggestion: see attached patch. 
Comment: patch is not perfect, but avoids loosing track. Patched source bootstraps a functional updated install (yet slightly incomplete wrt docs, etc., which is normal), using make -k.
Best.

**Comment by juliensf** [comment]
The master branch not compiling with 20.06.X is deliberate; we decided long ago that requiring the master branch compile with anything other than a recent ROTD would unnecessarily constrain development of the system.

**Comment by zsomogyi** [comment]
We provide ROTDs as source distributions because we do not guarantee that any ROTD can be built with the previous release, or even with e.g. a week-old ROTD. We often start using new language features soon after adding them to the language. So, as Julien said, "github master branch will not build using 20.06.1" is NOT a bug.

I just tried and failed to reproduce the first thing in your comment above. After downloading and unpacking
the most recent ROTD, I did ./configure --enable-minimal-install --prefix=...", and then make. This worked.
What problem were you trying to report by saying "mmc can no longer be bootstrapped by configuring
with --enable-minimal-install"?

**Comment by fabnicol** [comment]
> We provide ROTDs as source distributions because we do not guarantee that any ROTD can be built with the previous release, or even with e.g. a week-old ROTD. We often start using new language features soon after adding them to the language. So, as Julien said, "github master branch will not build using 20.06.1" is NOT a bug.

I understand the development policy. I did not make a bug report but suggested a possible way of smoothing out updates for users/testers. I understand there may be other priorities.
 
> I just tried and failed to reproduce the first thing in your comment above. After downloading and unpacking
> the most recent ROTD, I did ./configure --enable-minimal-install --prefix=...", and then make. This worked.
> What problem were you trying to report by saying "mmc can no longer be bootstrapped by configuring
> with --enable-minimal-install"?

I can confirm that `./configure --enable-minimal-install failed for the same (29 Jan.) ROTD with mmc 20.06.1. 
Bisecting the git repo led to the above commit reference, because every commit in between failed configuring with --enable-minimal-install. 
This happened when `--partial-inst-copy-2021-01-04` replaced `--unsigned-lt-2020-05-25` int the $BOOTSTRAP_MC command line options of configure.ac. So before this commit, configure worked and after it, config.log reported that the mmc compiler was too old.
After patching, bootstrapping was again possible up to HEAD. It may well be a platform and/or gcc-related issue.
Note: the bootcheck script failed too (stage 1 for ROTD), but this may be an outdated tool as indicated on the website.

**Comment by zsomogyi** [comment]
"So before this commit, configure worked and after it, config.log reported that the mmc compiler was too old."

Yes, of course. *That was deliberate*. It was *not* a platform or gcc issue; that was when we started to rely
on a recently-introduced part of the compiler.
