### ISSUE TITLE
Non-local gotos are fundamentally problematic at best

### ISSUE THREAD

**Issue by he32** [Mercury-Language/mercury#95]
As should be evident from the large comment block about `non-local gotos` in `configure.ac`, the following conditionals and the following entry from the GCC manual at https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html where it says

```
You may not use this mechanism to jump to code in a different function. If you do that,
totally unpredictable things happen. The best way to avoid this is to store the label 
address only in automatic variables and never pass it as an argument. 
```

I would suggest that this is problematic at best, and possibly something which relies on undefined behavior which may (and by the looks of it "will") change with compiler upgrades.  Another mechanism which doesn't extend beyond the defined support of the language and compilers should probably be sought out, or this will re-surface as an ever recurring source of problems.

**Comment by zsomogyi** [comment]
Yes, we know all that. That is why we use non-local gotos only if they work. If they don't work, you can still
compile Mercury programs, only they will be approximately twice as slow.
